import { isModerator } from "../services/jiraService.js";
import { getLogger } from "./logger.js";

export const isAuthenticated = (req, res, next) => {
    if (!req.session.user) {
        return res.redirect("/");
    }

    next();
};


//################## GENERATED BY AI ###################
export const attachRole = async (req, res, next) => {
    try {
        const { user } = req.session;

        if (!user) {
            return next();
        }

        const moderator = await isModerator(
            user.projectKey,
            user.accountId,
            user.domain,
            user.auth
        );

        req.userRole = moderator ? "moderator" : "player";

        next();
    } catch (err) {
       getLogger().error({ err }, "attachRole error");
       next(err);
    }
};
//######################################################
