#!/bin/sh

echo "Running ESLint..."
npm run lint

if [ $? -ne 0 ]; then
  echo "ESLint failed. Commit aborted."
  exit 1
fi

echo "Checking formatting with Prettier..."
npm run format:check

if [ $? -ne 0 ]; then
  echo "Prettier check failed. Commit aborted."
  exit 1
fi

echo "All checks passed ✅"